# Default values for main-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  name: nginx:1.7.9

# storage path for static files
staticFilesPath: "/tmp"